### ISSUE TITLE
譯名

### ISSUE THREAD

**Issue by www10177** [codebayin/Slime.Rancher.zh_TW#2]
## 需統一用字
# 物品
- Plort 結晶<br />
- Vacpack 吸取器<br />
- Vac tank 吸取槽<br/>
# 史萊姆名
- Largo 混種史萊姆<br/> 
- Gordo 胖胖史萊姆<br/> 
- The Tarr 焦油史萊姆<br/> 
# 果/菜/雞
- Heart Beet  甜心菜<br/>
- Cuberry 方莓<br/>
- Odd onion 怪洋蔥<br/>
- Stony Hen 石母雞<br/>
- Briar Hen 野母雞<br/>
# 地名
- the Far, Far Range 遠遠星球<br/>
- Indigo Quarry: 靛青礦場<br />
- the grotto 石窟<br/>
- Slime Sea 史萊姆海<br/>
- Moss Blanket 苔蘚之地<br/>
- dry reef 乾旱礁地<br/>
- Overgrowth 茂林<br/>
- the Range 一般指野外 <br/>
## 不確定的字
- Beatrix LeBeau : 主角名<br />
- Mosaic Slime(line 447) 應該是未來更新會出現的，文本裡沒介紹，暫時沒翻<br/>
- line 631

**Comment by nickexe** [comment]
我在考慮要不要把史萊姆的名稱改成 xx小史，感覺可愛一些
說明文字和描述的部分依舊用史萊姆

**Comment by www10177** [comment]
我也在想我前面好像翻得有點太正經了？感覺不夠可愛，他pedia的風格也是有點惡搞惡搞的感覺

**Comment by nickexe** [comment]
潤飾可以最後在一起調，先把內容完成，全部看過後，改起來會比較有一致性，只是想到什麼可以先用這種方法留下來，因為可能一覺醒來就忘了 XD

**Comment by nickexe** [comment]
Indigo Quarry 我 commit 的部分已經翻成靛藍礦場了，實際看了地圖，應該是靛青才對，先用一樣的名稱吧，之後用全部取代一起改

**Comment by nickexe** [comment]
The Moss Blanket 目前翻成 苔蘚地毯，我覺得不像地名，你看看有沒有更好的想法，這地方就是遍布苔蘚，所以英文名稱可以理解，中文就怪了一點

**Comment by www10177** [comment]
Indigo Quarry我備註上去了
苔蘚之地？不過blanket的感覺不好翻＠＠
另外是說我下禮拜有兩份作業要交，都還沒做ＱＱ所以本來就不快的進度可能會再稍微慢點

**Comment by nickexe** [comment]
其他部分都翻完了，名稱翻譯你可以直接參考翻好的用

另外 Gordo 胖胖史萊姆，我想之後把它改成 史大胖
Newbuck 就用元就好，buck 是美金，Newbuck 照翻是新美金，跟新台幣異曲同工，但我想用元即可
Largo 可能要想看看有沒有別的翻法，如果 Gordo 翻成 史大胖

**Comment by www10177** [comment]
OK

**Comment by nickexe** [comment]
遙遠之地要不要改成遠遠星球？內容有提到這是遠離地球的地方，所以應該是某個星球，用遠遠疊字感覺比較可愛，英文也是 Far Far

另外，git 的你會解決衝突嗎？如果我也翻 pedia.txt 的話，你就會遇到衝突，pull 前就肯定就得處理衝突

**Comment by www10177** [comment]
好啊，最後再來改成遠遠星球

應該會吧（？），試試看。
其實也不用了，我努力看看（？）今天搞不好能翻完

**Comment by www10177** [comment]
Hen hens are a special breed of chicken bred to survive the climate of the Far, Far Range.

這樣要將hen hens另外翻嗎？
或者直接翻成遠遠星球的母雞是特別品種的.......

**Comment by nickexe** [comment]
Hen hen 還是叫母雞好了，想不到可以翻什麼

**Comment by nickexe** [comment]
我這幾一兩天把 pedia.txt 改一下，你先看一下我翻的那些有沒有哪裡有問題，或是成就有沒有說明錯誤的，我特別在意那個旋轉木馬，因為名稱跟描述搭不上，我沒解過，不確定是不是跟呈現樣子有關

**Comment by nickexe** [comment]
這篇先 Close 吧
